######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 4 13:10:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += age.cpp
