######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 4 11:32:07 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
